version: '3.8'
services:
  auth_server:
    build: .
    command: python auth_server.py
    ports:
      - "5000:5000"
  resource_server:
    build: .
    command: python resource_server.py
    depends_on:
      - auth_server
    environment:
      INTROSPECT_URL: http://auth_server:5000/introspect
    ports:
      - "6000:6000"
