name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and start containers
        run: |
          docker-compose up -d --build
          sleep 10

      - name: Run tests
        run: pytest --junitxml=test-results.xml

      - name: Stop containers
        if: always()
        run: docker-compose down

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
