name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    env:
      AGENTS_FILE: /tmp/agents.json
      USERS_FILE: /tmp/users.json
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Initialize sample agent data
        run: |
          echo '{"agent-client-id": {"name": "CalendarAgent"}}' > "$AGENTS_FILE"
          echo '{"alice": "password123"}' > "$USERS_FILE"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          cd frontend && npm ci
      - name: Run frontend tests
        run: |
          cd frontend && npm test
      - name: Build frontend
        run: |
          cd frontend && npm run build
      - name: Run e2e tests
        run: |
          cd frontend && npm run test:e2e
      - name: Run python tests
        run: pytest -v
